version: '3'
services:
  quorumservice:
    build: ./Bobjac.QuorumService
    image: quorumservice
    container_name: quorumservice
    environment:
      REDIS: azure-vote-back
      CONTRACT_JSON_BLOB_URL: UPLOAD YOUR CONTRACT JSON FROM COMPILATION TO A BLOB STORAGE "UPLOAD YOUR CONTRACT JSON FROM COMPILATION TO A BLOB STORAGE ACCOUNT
      RPC: YOUR ABS NODE RPC ENDPOINT
      KEYVAULT_PRIVATEKEY_URI: THE URL TO THE ECDSA PRIVATE KEY WITHIN YOUR KEYVAULT
      APP_ID: THE APP_ID IN ACTIVE DIRECTORY FOR YOUR FUNCTION
      APP_SECRET: THE APP_SECRET IN ACTIVE DIRECTORY FOR YOUR FUNCTION
    ports:
        - "8080:80"