apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quorumservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: quorumservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: mymicroservice
        image: bobjacfoodsafety.azurecr.io/quorumservice:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: CONTRACT_JSON_BLOB_URL
          value: "UPLOAD YOUR CONTRACT JSON FROM COMPILATION TO A BLOB STORAGE ACCOUNT"
        - name: RPC 
          value: "YOUR ABS NODE RPC ENDPOINT"
        - name: KEYVAULT_PRIVATEKEY_URI
          value: "THE URL TO THE ECDSA PRIVATE KEY WITHIN YOUR KEYVAULT"
        - name: APP_ID
          value: "THE APP_ID IN ACTIVE DIRECTORY FOR YOUR FUNCTION"
        - name: APP_SECRET
          value: "THE APP_SECRET IN ACTIVE DIRECTORY FOR YOUR FUNCTION"
        
---
apiVersion: v1
kind: Service
metadata:
  name: quorumservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: quorumservice